# Dataset: https://www.cricinfo.com/records/highest-career-batting-average-282910

In [ ]:
import requests

In [ ]:
import requests

url = "https://www.cricinfo.com/records/highest-career-batting-average-282910"
output_filename = "dataset.csv"

# Send a GET request to the URL
response = requests.get(url, stream=True)

# Check if the download was successful
if response.status_code == 200:
    with open(output_filename, "wb") as file:
        for chunk in response.iter_content(chunk_size=8192):
            file.write(chunk)
    print(f"Dataset successfully downloaded as '{output_filename}'")
else:
    print(f"Failed to download. Status code: {response.status_code}")

Failed to download. Status code: 403

In [ ]:
import pandas as pd

In [ ]:
url = "https://www.cricinfo.com/records/highest-career-batting-average-282910"

In [ ]:
df = pd.read_csv("cricinfo_highest_career_batting_average.csv")

In [ ]:
#

In [ ]:
df.head()

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
4,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  60 non-null     object
 1   Span    60 non-null     object
 2   Mat     60 non-null     object
 3   Inns    60 non-null     int64
 4   NO      60 non-null     int64
 5   Runs    60 non-null     int64
 6   HS      60 non-null     object
 7   Ave     60 non-null     float64
 8   BF      60 non-null     object
 9   SR      60 non-null     object
 10  100     60 non-null     int64
 11  50      60 non-null     int64
 12  0       60 non-null     int64
 13  4s      60 non-null     object
 14  6s      60 non-null     object
dtypes: float64(1), int64(6), object(8)
memory usage: 7.2+ KB

In [ ]:
df.describe()

,Inns,NO,Runs,Ave,100,50,0
count,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000
mean,138.333333,14.450000,6549.950000,53.619667,19.716667,29.200000,7.950000
std,88.743711,11.423177,4118.199007,7.179386,12.714721,19.083936,5.573621
min,20.000000,1.000000,990.000000,48.000000,1.000000,3.000000,1.000000
25%,58.500000,5.000000,2625.000000,49.570000,7.750000,12.500000,3.000000
50%,134.500000,12.500000,6520.500000,51.950000,19.500000,28.500000,7.000000
75%,201.250000,19.000000,9327.500000,55.527500,29.250000,45.000000,12.000000
max,329.000000,49.000000,15921.000000,99.940000,51.000000,68.000000,22.000000

In [ ]:
# 1) rename some columns

In [ ]:
column_names_map = {
    "NO":"not_outs",
    "HS":"highest_inns_score",
    "Mat":"matches_played",
    "Inns":"innings_batted",
    "Runs":"runs_scored",
    "Ave":"batting_average",
    "BF":"balls_faced",
    "SR":"batting_strike_rate"
}

In [ ]:
df.rename(columns=column_names_map, inplace=True)

In [ ]:
df.columns = df.columns.str.lower()

In [ ]:
df.head()

,player,span,matches_played,innings_batted,not_outs,runs_scored,highest_inns_score,batting_average,balls_faced,batting_strike_rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
4,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6

In [ ]:
# check null values

In [ ]:
df.isna().sum()

player                 0
span                   0
matches_played         0
innings_batted         0
not_outs               0
runs_scored            0
highest_inns_score     0
batting_average        0
balls_faced            0
batting_strike_rate    0
100                    0
50                     0
0                      0
4s                     0
6s                     0
dtype: int64

In [ ]:
# check for duplicates

In [ ]:
df.duplicated().sum() # no duplicates hooray

np.int64(0)

In [ ]:
# split up span into start and end date + Career Length

In [ ]:
df['span']

0     1928-1948
1     2015-2016
2     1963-1970
3     1930-1954
4     1924-1935
5     1931-1939
6     1955-1968
7     1948-1958
8     1927-1947
9     1954-1974
10    2000-2015
11    1908-1930
12    1948-1960
13    1937-1955
14    2010-2026
15    1995-2013
16    1921-1929
17    1968-1973
18    1993-1995
19    2010-2026
20    1970-1984
21    1935-1951
22    1989-2013
23    2022-2026
24    2022-2026
25    1990-2006
26    1976-1993
27    1996-2012
28    1998-2010
29    2000-2017
30    1995-2012
31    1920-1929
32    1992-2002
33    2005-2013
34    1994-2015
35    1971-1987
36    1985-2004
37    1994-2009
38    2004-2018
39    1978-1994
40    1974-1991
41    2012-2026
42    1937-1957
43    1997-2014
44    1992-2007
45    1948-1963
46    1911-1928
47    2001-2013
48    2019-2021
49    2004-2015
50    1961-1966
51    1929-1949
52    1893-1905
53    2001-2013
54    1948-1963
55    1965-1981
56    2002-2014
57    1924-1934
58    1930-1938
59    1928-1934
Name: span, dtype: object

In [ ]:
df[['career_start_year','career_end_year']] = df['span'].str.split("-",expand=True)

In [ ]:
df['career_start_year'] = df['career_start_year'].str.strip()

In [ ]:
df['career_end_year'] = df['career_end_year'].str.strip()

In [ ]:
df['career_end_year'] = df['career_end_year'].astype("Int64")

In [ ]:
df['career_start_year'] = df['career_start_year'].astype("Int64")

In [ ]:
# career length

In [ ]:
df['career_length'] = df['career_end_year'] - df['career_start_year']

In [ ]:
df[['career_end_year','career_start_year','career_length']]

    career_end_year  career_start_year  career_length
0              1948               1928             20
1              2016               2015              1
2              1970               1963              7
3              1954               1930             24
4              1935               1924             11
5              1939               1931              8
6              1968               1955             13
7              1958               1948             10
8              1947               1927             20
9              1974               1954             20
10             2015               2000             15
11             1930               1908             22
12             1960               1948             12
13             1955               1937             18
14             2026               2010             16
15             2013               1995             18
16             1929               1921              8
17             1973               1968              5
18             1995               1993              2
19             2026               2010             16
20             1984               1970             14
21             1951               1935             16
22             2013               1989             24
23             2026               2022              4
24             2026               2022              4
25             2006               1990             16
26             1993               1976             17
27             2012               1996             16
28             2010               1998             12
29             2017               2000             17
30             2012               1995             17
31             1929               1920              9
32             2002               1992             10
33             2013               2005              8
34             2015               1994             21
35             1987               1971             16
36             2004               1985             19
37             2009               1994             15
38             2018               2004             14
39             1994               1978             16
40             1991               1974             17
41             2026               2012             14
42             1957               1937             20
43             2014               1997             17
44             2007               1992             15
45             1963               1948             15
46             1928               1911             17
47             2013               2001             12
48             2021               2019              2
49             2015               2004             11
50             1966               1961              5
51             1949               1929             20
52             1905               1893             12
53             2013               2001             12
54             1963               1948             15
55             1981               1965             16
56             2014               2002             12
57             1934               1924             10
58             1938               1930              8
59             1934               1928              6

In [ ]:
# drop span column

In [ ]:
df.drop(columns=['span'], inplace=True)

In [ ]:
# split player into player name and country code

In [ ]:
df[["player_name","country_code"]]=df['player'].str.split("(",expand=True)

In [ ]:
df['country_code'] = df['country_code'].str.replace(")","")

In [ ]:
df['player_name'] = df['player_name'].str.strip()

In [ ]:
df['country_code'] = df['country_code'].str.strip()

In [ ]:
df['player'] = df['player_name']

In [ ]:
df.head()

,player,matches_played,innings_batted,not_outs,runs_scored,highest_inns_score,batting_average,balls_faced,batting_strike_rate,100,50,0,4s,6s,career_start_year,career_end_year,career_length,player_name,country_code
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,20,DG Bradman,AUS
1,AC Voges,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,1,AC Voges,AUS
2,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,7,RG Pollock,SA
3,GA Headley,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954,24,GA Headley,WI
4,H Sutcliffe,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,11,H Sutcliffe,ENG

In [ ]:
df.drop(columns=['player_name'], inplace=True)

In [ ]:
df.head()

,player,matches_played,innings_batted,not_outs,runs_scored,highest_inns_score,batting_average,balls_faced,batting_strike_rate,100,50,0,4s,6s,career_start_year,career_end_year,career_length,country_code
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,20,AUS
1,AC Voges,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,1,AUS
2,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,7,SA
3,GA Headley,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954,24,WI
4,H Sutcliffe,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,11,ENG

In [ ]:
####

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   player               60 non-null     object
 1   matches_played       60 non-null     object
 2   innings_batted       60 non-null     int64
 3   not_outs             60 non-null     int64
 4   runs_scored          60 non-null     int64
 5   highest_inns_score   60 non-null     object
 6   batting_average      60 non-null     float64
 7   balls_faced          60 non-null     object
 8   batting_strike_rate  60 non-null     object
 9   100                  60 non-null     int64
 10  50                   60 non-null     int64
 11  0                    60 non-null     int64
 12  4s                   60 non-null     object
 13  6s                   60 non-null     object
 14  career_start_year    60 non-null     Int64
 15  career_end_year      60 non-null     Int64
 16  career_length        60 non-null     Int64
 17  country_code         60 non-null     object
dtypes: Int64(3), float64(1), int64(6), object(8)
memory usage: 8.7+ KB

In [ ]:
df['matches_played'] = df['matches_played'].str.replace(r"[^0-9]", "",regex=True)

In [ ]:
df['matches_played'] = df['matches_played'].astype("Int64")

In [ ]:
# highest_inns_score

In [ ]:
df['highest_inns_score'] = df['highest_inns_score'].str.replace(r"[^0-9]", "",regex=True)

In [ ]:
df['highest_inns_score'] = df['highest_inns_score'].astype("Int64")

In [ ]:
# balls_faced

In [ ]:
df['balls_faced']

0      9800+
1       2667
2      1707+
3       416+
4      6558+
5      1288+
6      4957+
7          -
8      7491+
9      4063+
10     22882
11     5363+
12         -
13     2844+
14     20237
15     28903
16      178+
17      665+
18      1823
19     18306
20    13079+
21      108+
22    29437+
23      2463
24      4182
25     19753
26    15164+
27     31258
28     14372
29     19375
30     22782
31     2035+
32     10636
33     12436
34     27395
35    14184+
36     22461
37     14349
38     16077
39    27002+
40     9613+
41     24714
42     2731+
43     22959
44     16345
45      488+
46      619+
47     10441
48      2445
49     15456
50      885+
51      158+
52         -
53     11641
54     1799+
55     8662+
56     15525
57     3118+
58     3217+
59     2110+
Name: balls_faced, dtype: object

In [ ]:
# question: fix rookie year

In [ ]:
df.head()

,player,matches_played,innings_batted,not_outs,runs_scored,highest_inns_score,batting_average,balls_faced,batting_strike_rate,100,50,0,4s,6s,career_start_year,career_end_year,career_length,country_code
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,20,AUS
1,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,1,AUS
2,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,7,SA
3,GA Headley,22,40,4,2190,270,60.83,416+,56.00,10,5,2,104+,1,1930,1954,24,WI
4,H Sutcliffe,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,11,ENG

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   player               60 non-null     object
 1   matches_played       60 non-null     Int64
 2   innings_batted       60 non-null     int64
 3   not_outs             60 non-null     int64
 4   runs_scored          60 non-null     int64
 5   highest_inns_score   60 non-null     Int64
 6   batting_average      60 non-null     float64
 7   balls_faced          60 non-null     object
 8   batting_strike_rate  60 non-null     object
 9   100                  60 non-null     int64
 10  50                   60 non-null     int64
 11  0                    60 non-null     int64
 12  4s                   60 non-null     object
 13  6s                   60 non-null     object
 14  career_start_year    60 non-null     Int64
 15  career_end_year      60 non-null     Int64
 16  career_length        60 non-null     Int64
 17  country_code         60 non-null     object
dtypes: Int64(5), float64(1), int64(6), object(6)
memory usage: 8.9+ KB

In [ ]:
df['batting_strike_rate'] = df['batting_strike_rate'].str.replace("-","0")

In [ ]:
df['batting_strike_rate'] = df['batting_strike_rate'].astype("Float64")

In [ ]:
df['balls_faced'] = df['balls_faced'].str.replace(r"[^0-9]","", regex=True)

In [ ]:
df['4s'] = df['4s'].str.replace(r"[^0-9]","", regex=True)

In [ ]:
df['4s'] = df['4s'].astype('Int64')

In [ ]:
df['6s'] = df['6s'].str.replace(r"[^0-9]","", regex=True)
df['6s'] = df['6s'].astype('Int64')