# **DATA CLEANING PROJECT**


The link to the dataset:
https://github.com/KeithGalli/Olympics-Dataset

This dataset contains biographical information about Olympic athletes, including their names, dates and places of birth, height, weight, and other personal details.

The dataset contains missing values, inconsistent formatting, and unstructured information that needs to be cleaned and standardized before analysis.

# **Tasks**

The main objective is to prepare the dataset for further analysis by performing the following data cleaning tasks:

1) Handle Missing Values — Identify and appropriately process missing or incomplete records.

2) Clean Height and Weight Data — Correct inconsistent measurements, separate combined values, and resolve incorrectly placed data.

3) Standardize Dates — Convert dates of birth into a consistent format.

4) Clean Birthplace Information — Standardize location names and extract geographical information into separate columns.

5) Fix Data Types — Convert columns into appropriate numeric, date, or text formats.

6) Standardize Text Values — Remove unnecessary characters, extra spaces, and formatting inconsistencies.

7) Validate the Cleaned Dataset — Check data consistency and ensure the dataset is ready for analysis.

## **P.S**:

This project was done for practice rather than presentation, so the cleaning steps may not be easy to follow.

My main goal here was to practice some data cleaning techniques, including regular expressions, string manipulation, handling missing values, data type conversion, date parsing, text standardization, splitting and extracting information from columns, and identifying and correcting inconsistent values.

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
bios = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/Olympics-Dataset/refs/heads/master/athletes/bios.csv")

In [ ]:
bios.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Roles          145500 non-null  object
 1   Sex            145500 non-null  object
 2   Full name      145500 non-null  object
 3   Used name      145500 non-null  object
 4   Born           143772 non-null  object
 5   Died           34042 non-null   object
 6   NOC            145499 non-null  object
 7   athlete_id     145500 non-null  int64
 8   Measurements   107833 non-null  object
 9   Affiliations   95832 non-null   object
 10  Nick/petnames  9145 non-null    object
 11  Title(s)       399 non-null     object
 12  Other names    7167 non-null    object
 13  Nationality    8259 non-null    object
 14  Original name  30739 non-null   object
 15  Name order     7844 non-null    object
dtypes: int64(1), object(15)
memory usage: 17.8+ MB

In [ ]:
# lets copy df

In [ ]:
df = bios.copy()

In [ ]:
df.head(1)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
len(df)

145500

In [ ]:
len(df)==df['Used name'].str.contains("•").sum()

np.True_

In [ ]:
df['name'] = df['Used name'].str.replace('•'," ")

In [ ]:
# split height and weight

In [ ]:
df['Measurements'].value_counts(dropna=False)

Measurements
NaN                  37667
180 cm / 75 kg         556
180 cm / 70 kg         487
170 cm / 60 kg         464
175 cm / 70 kg         462
                     ...
148 cm / 34 kg           1
181 cm / 56 kg           1
175 cm / 85-89 kg        1
206 cm / 137 kg          1
205 cm / 93 kg           1
Name: count, Length: 4659, dtype: int64

In [ ]:
df[~df['Measurements'].str.contains(" / ", na=False)]['Measurements'].value_counts()

Measurements
170 cm    252
180 cm    251
178 cm    235
173 cm    192
183 cm    189
         ...
149 cm      1
168 kg      1
218 cm      1
147 kg      1
140 cm      1
Name: count, Length: 219, dtype: int64

In [ ]:
#

In [ ]:
df[['height','weight']] = df['Measurements'].str.split("/", expand=True)

In [ ]:
#

In [ ]:
df[~df['Measurements'].str.contains('/',na=False)]

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height,weight
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN
7,Competed in Olympic Games,Male,Henri Jean•Cochet,Henri•Cochet,"14 December 1901 in Villeurbanne, Rhône (FRA)","2 April 1987 in Saint-Germain-en-Laye, Yveline...",France,8,NaN,NaN,Le Magicien,NaN,NaN,NaN,NaN,NaN,Henri Cochet,NaN,NaN
8,Competed in Olympic Games,Male,Marcel•Cousin,Marcel•Cousin,"4 August 1896 in Nîmes, Gard (FRA)","1 August 1986 in Nîmes, Gard (FRA)",France,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Marcel Cousin,NaN,NaN
9,Competed in Olympic Games,Male,Luc Henri Hervé Guy•Gardye de la Chapelle,Guy•de la Chapelle,"16 July 1868 in Farges-Allichamps, Cher (FRA)",27 August 1923,France,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Guy de la Chapelle,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145492,Competed in Olympic Games,Male,Carlos•García-Ordóñez Montalvo,Carlos•García-Ordóñez,"24 April 1927 in La Habana (Havana), Ciudad de...","24 November 2019 in Miami, Florida (USA)",Cuba,149219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Carlos García-Ordóñez,NaN,NaN
145493,Competed in Olympic Games,Female,Landysh Ilsurovna•Falyakhova,Landysh•Falyakhova,"31 August 1998 in Dva Polya Artash, Respublika...",NaN,ROC,149220,NaN,"SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)",NaN,NaN,NaN,NaN,Ландыш Ильсуровна•Фаляхова,NaN,Landysh Falyakhova,NaN,NaN
145494,Competed in Olympic Games,Male,George Fletcher•Wright,George•Wright,"21 July 1890 in Toronto, Ontario (CAN)","28 January 1973 in Los Angeles, California (USA)",Canada,149221,183 cm,"Argonaut Rowing Club, Toronto (CAN)",NaN,NaN,NaN,NaN,NaN,NaN,George Wright,183 cm,None
145498,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,André Foussard,166 cm,None
145499,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill•Phillips,"15 July 1913 in Dulwich Hill, New South Wales ...","20 October 2003 in Sydney, New South Wales (AUS)",Australia,149814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bill Phillips,NaN,NaN

In [ ]:
df[df['Measurements'].str.contains('-',na=False)]

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height,weight
432,Competed in Olympic Games,Female,Minna Kaarina•Heinonen (-Koivisto),Minna•Heinonen,"26 August 1967 in Harjavalta, Satakunta (FIN)",NaN,Finland,433,173 cm / 64-66 kg,Harjavallan Jousiampujat,NaN,NaN,NaN,NaN,NaN,NaN,Minna Heinonen,173 cm,64-66 kg
435,Competed in Olympic Games,Female,Jutta Anneli•Poikolainen (Vähäoja-),Jutta•Poikolainen,"15 March 1963 in Tampere, Pirkanmaa (FIN)",NaN,Finland,436,176 cm / 63-65 kg,"Amarco, Hyvinkää (FIN)",NaN,NaN,NaN,NaN,NaN,NaN,Jutta Poikolainen,176 cm,63-65 kg
437,Competed in Olympic Games,Male,Ismo Kalevi•Falck,Ismo•Falck,"22 August 1966 in Paltamo, Kainuu (FIN)",NaN,Finland,438,172 cm / 67-74 kg,"Suomussalmen Vastus, Suomussalmi (FIN)",NaN,NaN,NaN,NaN,NaN,NaN,Ismo Falck,172 cm,67-74 kg
440,Competed in Olympic Games,Male,Kauko Markus•Laasonen,Kauko•Laasonen,"8 January 1951 in Kesälahti, Pohjois-Karjala (...",NaN,Finland,441,178 cm / 73-75 kg,"Porin Jousiampujat, Pori (FIN)",Kake,NaN,NaN,NaN,NaN,NaN,Kauko Laasonen,178 cm,73-75 kg
441,Competed in Olympic Games,Male,Kyösti Kalevi•Laasonen,Kyösti•Laasonen,"27 September 1945 in Kitee, Pohjois-Karjala (FIN)",NaN,Finland,442,173 cm / 63-65 kg,"Porin Jousiampujat, Pori (FIN)",Kössi,NaN,NaN,NaN,NaN,NaN,Kyösti Laasonen,173 cm,63-65 kg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128984,Competed in Olympic Games,Female,Anna Sergeyevna•Sen,Anna•Sen,"3 December 1990 in Krasnodar, Krasnodar Kray (...",NaN,ROC Russian Federation,131580,186 cm / 81-85 kg,"Rostov-Don, Rostov-on-Don (RUS)",NaN,NaN,NaN,NaN,Анна Сергеевна•Сень,NaN,Anna Sen,186 cm,81-85 kg
128986,Competed in Olympic Games,Female,Darya Yevgenyevna•Dmitriyeva,Darya•Dmitriyeva,"9 August 1995 in Togliatti, Samara (RUS)",NaN,ROC Russian Federation,131582,178 cm / 71-74 kg,"HK Lada Toliatti, Togliatti (RUS) / CSKA, Mosc...",NaN,NaN,NaN,NaN,Дарья Евгеньевна•Дмитриева,NaN,Darya Dmitriyeva,178 cm,71-74 kg
128990,Competed in Olympic Games,Female,Polina Viktorovna•Kuznetsova (Vyakhireva-),Polina•Kuznetsova,"10 June 1987 in Shopokov, Chuy (KGZ)",NaN,ROC Russian Federation,131586,168 cm / 60-64 kg,"HC Astrakhanochka [RUS) / Rostov-Don, Rostov-o...",NaN,NaN,NaN,NaN,Полина Викторовна•Кузнецова (Вяхирева-),NaN,Polina Kuznetsova,168 cm,60-64 kg
131318,Competed in Olympic Games • Other,Male,Lasha•Talakhadze,Lasha•Talakhadze,"2 October 1993 in Sachkhere, Imereti (GEO)",NaN,Georgia,134095,197 cm / 158-160 kg,NaN,NaN,NaN,NaN,NaN,ლაშა•ტალახაძე,NaN,Lasha Talakhadze,197 cm,158-160 kg
133728,Competed in Olympic Games,Male,Ekemini Jakob•Bassey,Ekemini•Bassey,"22 October 1987 in Wien (Vienna), Wien (AUT)",NaN,Austria,136717,175 cm / 85-89 kg,Sportunion St. Polten (AUT) / Team Teigl,NaN,NaN,NaN,NaN,NaN,NaN,Ekemini Bassey,175 cm,85-89 kg

In [ ]:
# lets look at height

In [ ]:
pass_weight_mask = df['height'].str.contains("kg", na=False)

In [ ]:
df.loc[
    pass_weight_mask, 'weight'
] = df.loc[
    pass_weight_mask, 'height'
]

In [ ]:
df.loc[
    pass_weight_mask, 'height'
] = np.nan

In [ ]:
df['height'].str.contains('kg', na=False).sum()

np.int64(0)

In [ ]:
# so kg in its place - good

In [ ]:
df['height'].str.contains(',', na=False).sum()

np.int64(0)

In [ ]:
df['height'].str.contains(r'[^0-9 cm]',regex=True, na=False).sum()

np.int64(0)

In [ ]:
df['height'] = df['height'].str.replace('cm',"").str.strip().astype("Float64")

In [ ]:
df['height'].value_counts()

height
180.0    6617
170.0    5944
178.0    5617
175.0    5408
183.0    4490
         ...
130.0       2
219.0       2
128.0       1
131.0       1
226.0       1
Name: count, Length: 95, dtype: Int64

In [ ]:
# now lets clean 'weight

In [ ]:
df['weight'].str.contains('-', na=False).sum()

np.int64(943)

In [ ]:
df['weight'].str.contains(',', na=False).sum()

np.int64(86)

In [ ]:
df['weight'].str.contains(r'[^0-9 kg,-]',regex=True, na=False).sum()

np.int64(0)

In [ ]:
df['weight_clean'] = df['weight']

In [ ]:
df['weight'].str.contains('kg', na=True).sum()

np.int64(145500)

In [ ]:
# it means every cell is kg then we can deleted this part "kg"

In [ ]:
df['weight_clean']=df['weight_clean'].str.replace("kg","")

In [ ]:
df[df['weight'].str.contains(',', na=False)]

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height,weight,weight_clean
37121,Competed in Olympic Games,Male,Guy Oliver•Nickalls,Guy O.•Nickalls,"4 April 1899 in Wycombe, England (GBR)","26 April 1974 in London, England (GBR)",Great Britain,37416,"74, 82 kg",NaN,Gully,NaN,NaN,NaN,NaN,NaN,Guy O. Nickalls,<NA>,"74, 82 kg","74, 82"
54695,Competed in Olympic Games,Male,Abdel Manaane•Yahiaoui,Abdel Manaane•Yahiaoui,6 December 1966,NaN,Algeria,55089,"68, 70 kg",NaN,NaN,NaN,NaN,NaN,عبد المنان•يحياوي,NaN,Abdel Manaane Yahiaoui,<NA>,"68, 70 kg","68, 70"
54705,Competed in Olympic Games,Male,Osvaldo Alberto•Forte,Osvaldo•Forte,"1 June 1919 in Buenos Aires, Ciudad Autónoma d...",29 July 2005,Argentina,55099,"81, 82 kg","San Lorenzo, Buenos Aires (ARG)",NaN,NaN,NaN,NaN,NaN,NaN,Osvaldo Forte,<NA>,"81, 82 kg","81, 82"
54706,Competed in Olympic Games,Male,Marcelo Gustavo•Gandolfo López,Marcelo•Gandolfo,6 July 1972,NaN,Argentina,55100,"60, 69 kg",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Marcelo Gandolfo,<NA>,"60, 69 kg","60, 69"
54711,Competed in Olympic Games,Male,Gustavo A.•Majauskas Manfredi,Gustavo•Majauskas,12 January 1966,NaN,Argentina,55105,"60, 64 kg",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Gustavo Majauskas,<NA>,"60, 64 kg","60, 64"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116046,Competed in Olympic Games,Male,Rasul•Abduraim,Rasul•Abduraim,"13 December 1988 in Panfilov district, Chuy (KGZ)",NaN,Kyrgyzstan,117425,"183 cm / 68, 80 kg",NaN,NaN,NaN,NaN,NaN,Расул•Абдураим,NaN,Rasul Abduraim,183.0,"68, 80 kg","68, 80"
116061,Competed in Olympic Games,Male,Sébastien•Michaud,Sébastien•Michaud,"7 May 1987 in Joliette, Québec (CAN)",NaN,Canada,117441,"185 cm / 78, 80 kg","Club Taekwondo Ste-Foy, Québec City (CAN)",NaN,NaN,NaN,NaN,NaN,NaN,Sébastien Michaud,185.0,"78, 80 kg","78, 80"
116071,Competed in Olympic Games,Male,Liu•Xiaobo,Liu•Xiaobo,"16 January 1984 in Beijing, Beijing (CHN)",NaN,People's Republic of China,117452,"201 cm / 100, 104 kg","Beijing Municipal Taekwondo Team, Beijing (CHN)",NaN,NaN,NaN,NaN,刘•哮波,Oriental,Liu Xiaobo,201.0,"100, 104 kg","100, 104"
116073,Competed in Olympic Games,Male,Akmal•Ergashev,Akmal•Ergashev,"16 December 1982 in ?, Fargona (UZB)",NaN,Uzbekistan,117454,"190 cm / 86, 90 kg",NaN,NaN,NaN,NaN,NaN,Акмаль•Эргашев,NaN,Akmal Ergashev,190.0,"86, 90 kg","86, 90"
120129,Competed in Olympic Games,Female,Rangsiya•Nisaisom,Rangsiya•Nisaisom,11 June 1994,NaN,Thailand,121990,"165 cm / 62, 67 kg",NaN,NaN,NaN,NaN,NaN,รังสิญา•นิสัยสม,NaN,Rangsiya Nisaisom,165.0,"62, 67 kg","62, 67"

In [ ]:
# lets split by -

In [ ]:
df[['w1','w2']] = df['weight_clean'].str.split("-",expand=True)

In [ ]:
df['w1'] = df['w1'].str.strip()

In [ ]:
df['w2'] = df['w2'].str.strip()

In [ ]:
df['w1'].str.contains(",",na=False).sum()

np.int64(86)

In [ ]:
# now by comma

In [ ]:
comma_mask =(
    df['weight_clean'].str.contains(",",na=False)
)

In [ ]:
#

In [ ]:
df.loc[comma_mask, ["w1", "w2"]] = (
    df.loc[comma_mask, "weight_clean"]
    .str.split(",", n=1, expand=True)
    .to_numpy()
)

In [ ]:
df['w1'].str.contains('-', na=False).sum()

np.int64(0)

In [ ]:
df['w1'].str.contains(' ', na=False).sum()

np.int64(22)

In [ ]:
df[df['w2'].str.contains(',', na=False)]

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Other names,Nationality,Original name,Name order,name,height,weight,weight_clean,w1,w2
56164,Competed in Olympic Games,Male,Chon•Chol-Ho,Chon•Chol-Ho,7 April 1969,NaN,Democratic People's Republic of Korea,56563,"76, 77, 79 kg",NaN,...,Jon Chol-Ho,NaN,NaN,Oriental,Chon Chol-Ho,<NA>,"76, 77, 79 kg","76, 77, 79",76,"77, 79"
56630,Competed in Olympic Games,Male,"Roberto Antonio ""Tony""•Urrutia Herdez",Tony•Urrutia,7 December 1957 in ? (CUB),NaN,Cuba United States,57033,"67, 75, 82 kg",NaN,...,NaN,NaN,NaN,NaN,Tony Urrutia,<NA>,"67, 75, 82 kg","67, 75, 82",67,"75, 82"

In [ ]:
df['w1'].str.contains(",", na=False).sum()

np.int64(0)

In [ ]:
df['w1'].str.contains("[^0-9]", na=False).sum()

np.int64(0)

In [ ]:
df['w1'] = df['w1'].astype("Float64")

In [ ]:
# df["w1"] is fine. Now w2 is left to clean

In [ ]:
df["w2"].value_counts(dropna=False)

w2
None    106804
NaN      37667
82          42
70          38
80          38
         ...
 86          1
122          1
107          1
155          1
170          1
Name: count, Length: 143, dtype: int64

In [ ]:
df[df['w2'].str.contains(",", na=False)][['w1','w2']]

         w1      w2
56164  76.0  77, 79
56630  67.0  75, 82

In [ ]:
df['w2'] = df['w2'].str.rstrip()

In [ ]:
# lets try to do that with copy of df, let call it df_t

In [ ]:
still_coma_mask = df['w2'].str.contains(",", na=False)

In [ ]:
df.loc[
    still_coma_mask, 'w2'
].str.split(',')

56164    [77,  79]
56630    [75,  82]
Name: w2, dtype: object

In [ ]:
df.loc[
    still_coma_mask, 'w2'
].str.split(',').str[0]

56164    77
56630    75
Name: w2, dtype: object

In [ ]:
df.loc[
    still_coma_mask, 'w2'
].str.split(',').str[1]

56164     79
56630     82
Name: w2, dtype: object

In [ ]:
(df.loc[
    still_coma_mask, 'w2'
].str.split(',').str[0].astype("Float64")+df.loc[
    still_coma_mask, 'w2'
].str.split(',').str[1].astype("Float64")) / 2

56164    78.0
56630    78.5
Name: w2, dtype: Float64

In [ ]:
#lets save these counted avg for those two rows that had three commas !!!

In [ ]:
df.loc[
    still_coma_mask, 'w2'
] = (df.loc[
    still_coma_mask, 'w2'
].str.split(',').str[0].astype("Float64")+df.loc[
    still_coma_mask, 'w2'
].str.split(',').str[1].astype("Float64")) / 2

In [ ]:
df.loc[
    still_coma_mask, 'w2'
]

56164    78.0
56630    78.5
Name: w2, dtype: object

In [ ]:
# lets check for changes in w2

In [ ]:
df['w2'] = df['w2'].str.strip()

In [ ]:
df['w2'].str.contains("[^0-9]",na=False).sum()

np.int64(0)

In [ ]:
df['w2'] = df['w2'].astype('Float64')

In [ ]:
df['w2'].dtype

Float64Dtype()

In [ ]:
df

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Other names,Nationality,Original name,Name order,name,height,weight,weight_clean,w1,w2
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,...,NaN,NaN,NaN,NaN,Jean-François Blanchy,<NA>,NaN,NaN,<NA>,<NA>
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,NaN,NaN,Arnaud Boetsch,183.0,76 kg,76,76.0,<NA>
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,Jean Borotra,183.0,76 kg,76,76.0,<NA>
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,NaN,NaN,Jacques Brugnon,168.0,64 kg,64,64.0,<NA>
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,Albert Canet,<NA>,NaN,NaN,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,Competed in Olympic Games,Female,Polina•Luchnikova,Polina•Luchnikova,"30 January 2002 in Serov, Sverdlovsk (RUS)",NaN,ROC,149222,167 cm / 61 kg,"Agidel, Ufa (RUS)",...,NaN,NaN,NaN,NaN,Polina Luchnikova,167.0,61 kg,61,61.0,<NA>
145496,Competed in Olympic Games,Female,Valeriya Sergeyevna•Merkusheva,Valeriya•Merkusheva,"20 September 1999 in Moskva (Moscow), Moskva (...",NaN,ROC,149223,168 cm / 65 kg,"SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)",...,NaN,NaN,Валерия Сергеевна•Меркушева,NaN,Valeriya Merkusheva,168.0,65 kg,65,65.0,<NA>
145497,Competed in Olympic Games,Female,Yuliya•Smirnova,Yuliya•Smirnova,"8 May 1998 in Kotlas, Arkhangelsk (RUS)",NaN,ROC,149224,163 cm / 55 kg,"Agidel, Ufa (RUS)",...,NaN,NaN,Юлия•Смирнова,NaN,Yuliya Smirnova,163.0,55 kg,55,55.0,<NA>
145498,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",...,NaN,NaN,NaN,NaN,André Foussard,166.0,None,None,<NA>,<NA>
145499,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill•Phillips,"15 July 1913 in Dulwich Hill, New South Wales ...","20 October 2003 in Sydney, New South Wales (AUS)",Australia,149814,NaN,NaN,...,NaN,NaN,NaN,NaN,Bill Phillips,<NA>,NaN,NaN,<NA>,<NA>

In [ ]:
# тепер нарешті зміними weight_clean
# 1)якщо у weight clean був діапазон значень, або декілька значень через кому, то йому запишемо середнє всіх тих значень
# 2)якщо було лише одне значення, то його і запишемо

In [ ]:
weight_range_mask = (
    df['w1'].notna() & df['w2'].notna()
)

In [ ]:
df.loc[
    weight_range_mask
].head(2)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Other names,Nationality,Original name,Name order,name,height,weight,weight_clean,w1,w2
432,Competed in Olympic Games,Female,Minna Kaarina•Heinonen (-Koivisto),Minna•Heinonen,"26 August 1967 in Harjavalta, Satakunta (FIN)",NaN,Finland,433,173 cm / 64-66 kg,Harjavallan Jousiampujat,...,NaN,NaN,NaN,NaN,Minna Heinonen,173.0,64-66 kg,64-66,64.0,66.0
435,Competed in Olympic Games,Female,Jutta Anneli•Poikolainen (Vähäoja-),Jutta•Poikolainen,"15 March 1963 in Tampere, Pirkanmaa (FIN)",NaN,Finland,436,176 cm / 63-65 kg,"Amarco, Hyvinkää (FIN)",...,NaN,NaN,NaN,NaN,Jutta Poikolainen,176.0,63-65 kg,63-65,63.0,65.0

In [ ]:
# запишемо середнє значення

In [ ]:
df.loc[
    weight_range_mask,'weight_clean'
] = (df.loc[ weight_range_mask,'w1']+df.loc[weight_range_mask,'w2'])/2

In [ ]:
#тепер де було просто одне значення

In [ ]:
(~weight_range_mask)

np.int64(145500)

In [ ]:
df.loc[
    ~weight_range_mask,'weight_clean'
] = df.loc[~weight_range_mask, 'w1']

In [ ]:
# топер дочистимо: strip(), змінимо тип даних
print(df['weight_clean'].dtype)

object

In [ ]:
df['weight_clean'].mean()

np.float64(71.97994914115728)

In [ ]:
df['weight_clean'].map(type).value_counts()

weight_clean
<class 'float'>                          104210
<class 'pandas._libs.missing.NAType'>     41290
Name: count, dtype: int64

In [ ]:
# бачимо є пропущені значення

In [ ]:
# зробимо тип стовпця правильним

In [ ]:
df['weight_clean'] = pd.to_numeric(
    df['weight_clean'],
    errors='coerce'
)

In [ ]:
df['weight_clean'].dtype

dtype('float64')

In [ ]:
df['weight_clean'].describe()

count    104210.000000
mean         71.979949
std          14.566444
min          25.000000
25%          62.000000
50%          71.000000
75%          80.000000
max         214.000000
Name: weight_clean, dtype: float64

In [ ]:
# Тепер все добре
# тепер перепишемо значення до weight

In [ ]:
df['weight'] = df['weight_clean']

In [ ]:
# дропнемо всі допоміжні стовпчики

In [ ]:
df.drop(columns=['weight_clean','w1','w2'], inplace=True)

In [ ]:
# чекнемо тип даинх чи все окей
df['height'].dtype

dtype('float64')

In [ ]:
df['height'] = df['height'].astype('float64')

In [ ]:
# Name order - not yet

In [ ]:
df['Name order'].value_counts(dropna=False)

Name order
NaN         137656
Oriental      7844
Name: count, dtype: int64

In [ ]:
# Roles - not yet

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 19 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Roles          145500 non-null  object
 1   Sex            145500 non-null  object
 2   Full name      145500 non-null  object
 3   Used name      145500 non-null  object
 4   Born           143772 non-null  object
 5   Died           34042 non-null   object
 6   NOC            145499 non-null  object
 7   athlete_id     145500 non-null  int64
 8   Measurements   107833 non-null  object
 9   Affiliations   95832 non-null   object
 10  Nick/petnames  9145 non-null    object
 11  Title(s)       399 non-null     object
 12  Other names    7167 non-null    object
 13  Nationality    8259 non-null    object
 14  Original name  30739 non-null   object
 15  Name order     7844 non-null    object
 16  name           145500 non-null  object
 17  height         106651 non-null  float64
 18  weight         104210 non-null  float64
dtypes: float64(2), int64(1), object(16)
memory usage: 21.1+ MB

In [ ]:
# Sex - все добре

In [ ]:
df['Sex'].value_counts()

Sex
Male      106325
Female     39175
Name: count, dtype: int64

In [ ]:
# Full name - все добре

In [ ]:
# Born

In [ ]:
df['born_date'] = df['Born'].str.extract(r"(\d+ \w+ \d{4})")

In [ ]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Title(s),Other names,Nationality,Original name,Name order,name,height,weight,NOC_clean,born_date
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN,France,12 December 1886
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183.0,76.0,France,1 April 1969
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Jean Borotra,183.0,76.0,France,13 August 1898
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,168.0,64.0,France,11 May 1895
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN,France,17 April 1878

In [ ]:
#small_data = pd.DataFrame(['1895', '12 December 1900'], columns=['Born'])
date_pattern=r"(\d+ \w+ \d{4}|\d{4})"
df['born_date'] = df["Born"].str.extract(date_pattern)

In [ ]:
df['born_date'] = pd.to_datetime(df['born_date'], format="mixed", errors = 'coerce')

In [ ]:
df[~(df['Born'].str.contains(r"(\d+ \w+ \d{4})", regex=True, na=True))]

/tmp/ipykernel_1258/3507302011.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[~(df['Born'].str.contains(r"(\d+ \w+ \d{4})", regex=True, na=True))]

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Other names,Nationality,Original name,Name order,name,height,weight,NOC_clean,born_date,died_date
91,Competed in Olympic Games,Male,Lionel Hunter•Escombe,Lionel•Escombe,"1876 in Natal, KwaZulu-Natal (RSA)","15 October 1914 in Brentford, England (GBR)",Great Britain,92,NaN,NaN,...,NaN,NaN,NaN,NaN,Lionel Escombe,NaN,NaN,Great Britain,1876,1914-10-15
179,Competed in Olympic Games,Male,Pantelis•Papadopoulos,Pantelis•Papadopoulos,1902,1987,Greece,180,NaN,Lawn Tennis Athens,...,NaN,NaN,Παντελής•Παπαδόπουλος,NaN,Pantelis Papadopoulos,NaN,NaN,Greece,1902,1987-01-01
552,Competed in Olympic Games,Female,Emily Jane•Rushton (Ormrod-),Emily•Rushton,"1850 in Halliwell, England (GBR)","30 June 1939 in Barnacre-with-Bonds, Garstang,...",Great Britain,554,NaN,"Barnacre Archers, Barnacre-with-Bonds, Garstan...",...,NaN,NaN,NaN,NaN,Emily Rushton,NaN,NaN,Great Britain,1850,1939-06-30
561,Competed in Olympic Games,Female,Hilda•Williams,Hilda•Williams,"1876 in Marton, England (GBR)","10 July 1922 in Surbiton, England (GBR)",Great Britain,563,NaN,"Mid Surrey Archery Club, Surbiton (GBR)",...,NaN,NaN,NaN,NaN,Hilda Williams,NaN,NaN,Great Britain,1876,1922-07-10
667,Competed in Olympic Games,Female,Marie•Jones,Marie•Jones,1896,NaN,Belgium,670,NaN,NaN,...,NaN,NaN,NaN,NaN,Marie Jones,NaN,NaN,Belgium,1896,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118318,Competed in Olympic Games,Male,"J. Edward ""Eddie""•Heron",Eddie•Heron,"1910 in Dublin, Dublin (IRL)","23 April 1985 in Dublin, Dublin (IRL)",Ireland,120008,NaN,"Sandycove Swimming Club, Sandycove (IRL)",...,NaN,NaN,NaN,NaN,Eddie Heron,NaN,NaN,Ireland,1910,1985-04-23
118344,Competed in Olympic Games,Female,Lilo•Mund Borgs,Lilo•Mund,"1939 in Santiago, Santiago Metropolitan (CHI)",NaN,Chile,120048,NaN,NaN,...,NaN,NaN,NaN,NaN,Lilo Mund,NaN,NaN,Chile,1939,NaT
124915,Competed in Olympic Games,Male,"William•Taylor, Jr.",William•Taylor,"1870 in Hoxton, England (GBR)",NaN,Great Britain,127258,NaN,"Essex Beagles, Barking (GBR)",...,NaN,NaN,NaN,NaN,William Taylor,NaN,NaN,Great Britain,1870,NaT
126482,Competed in Olympic Games,Male,Cornelius•von Lubowiecki,Cornelius•von Lubowiecki,1876,NaN,Austria,128837,NaN,"Wiener AC, Wien (AUT)",...,NaN,NaN,NaN,NaN,Cornelius von Lubowiecki,NaN,NaN,Austria,1876,NaT
135276,Competed in Olympic Games,Male,"Louis•Dufour, Sr.","Louis•Dufour, Sr.","1873 in Les Avants, Vaud (SUI)",12 April 1944,Switzerland,138439,NaN,"Les Avants HC, Les Avants (SUI)",...,NaN,NaN,NaN,NaN,"Louis Dufour, Sr.",NaN,NaN,Switzerland,1873,1944-04-12

In [ ]:
# the same for Died date
df['died_date'] = df["Died"].str.extract(date_pattern)
df['died_date'] = pd.to_datetime(df['died_date'], format="mixed", errors = 'coerce')

In [ ]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Other names,Nationality,Original name,Name order,name,height,weight,NOC_clean,born_date,died_date
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,...,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN,France,12 December 1886,1960-10-02
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,NaN,NaN,Arnaud Boetsch,183.0,76.0,France,1 April 1969,NaT
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,Jean Borotra,183.0,76.0,France,13 August 1898,1994-07-17
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,NaN,NaN,Jacques Brugnon,168.0,64.0,France,11 May 1895,1978-03-20
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN,France,17 April 1878,1930-07-25

In [ ]:
# get the born_city, born_region, born_country

In [ ]:
location_pattern = r'in ([\w\s-]+), ([\w\s-]+) \((\w+)\)'

In [ ]:
df[['born_city', 'born_region', 'born_country']] = df['Born'].str.extract(location_pattern, expand=True)

In [ ]:
df

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Name order,name,height,weight,NOC_clean,born_date,died_date,born_city,born_region,born_country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,...,NaN,Jean-François Blanchy,NaN,NaN,France,12 December 1886,1960-10-02,Bordeaux,Gironde,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,Arnaud Boetsch,183.0,76.0,France,1 April 1969,NaT,Meulan,Yvelines,FRA
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,Jean Borotra,183.0,76.0,France,13 August 1898,1994-07-17,Biarritz,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,Jacques Brugnon,168.0,64.0,France,11 May 1895,1978-03-20,Paris VIIIe,Paris,FRA
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,NaN,Albert Canet,NaN,NaN,France,17 April 1878,1930-07-25,Wandsworth,England,GBR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,Competed in Olympic Games,Female,Polina•Luchnikova,Polina•Luchnikova,"30 January 2002 in Serov, Sverdlovsk (RUS)",NaN,ROC,149222,167 cm / 61 kg,"Agidel, Ufa (RUS)",...,NaN,Polina Luchnikova,167.0,61.0,ROC,30 January 2002,NaT,Serov,Sverdlovsk,RUS
145496,Competed in Olympic Games,Female,Valeriya Sergeyevna•Merkusheva,Valeriya•Merkusheva,"20 September 1999 in Moskva (Moscow), Moskva (...",NaN,ROC,149223,168 cm / 65 kg,"SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)",...,NaN,Valeriya Merkusheva,168.0,65.0,ROC,20 September 1999,NaT,NaN,NaN,NaN
145497,Competed in Olympic Games,Female,Yuliya•Smirnova,Yuliya•Smirnova,"8 May 1998 in Kotlas, Arkhangelsk (RUS)",NaN,ROC,149224,163 cm / 55 kg,"Agidel, Ufa (RUS)",...,NaN,Yuliya Smirnova,163.0,55.0,ROC,8 May 1998,NaT,Kotlas,Arkhangelsk,RUS
145498,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",...,NaN,André Foussard,166.0,NaN,France,19 May 1899,1986-03-18,Niort,Deux-Sèvres,FRA
145499,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill•Phillips,"15 July 1913 in Dulwich Hill, New South Wales ...","20 October 2003 in Sydney, New South Wales (AUS)",Australia,149814,NaN,NaN,...,NaN,Bill Phillips,NaN,NaN,Australia,15 July 1913,2003-10-20,Dulwich Hill,New South Wales,AUS

In [ ]:
df['born_city'].value_counts().head(10)

born_city
Budapest          1378
Oslo               708
Stockholm          629
Toronto            579
Buenos Aires       538
Sydney             497
Montréal           468
Berlin             467
Helsinki           439
Rio de Janeiro     433
Name: count, dtype: int64

In [ ]:
df.value_counts("born_city", ascending=False).head(10)

born_city
Budapest          1378
Oslo               708
Stockholm          629
Toronto            579
Buenos Aires       538
Sydney             497
Montréal           468
Berlin             467
Helsinki           439
Rio de Janeiro     433
Name: count, dtype: int64

In [ ]:
# remove unnecessary columns

In [ ]:
df.head(1)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Name order,name,height,weight,NOC_clean,born_date,died_date,born_city,born_region,born_country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,...,NaN,Jean-François Blanchy,NaN,NaN,France,12 December 1886,1960-10-02,Bordeaux,Gironde,FRA

In [ ]:
columns_to_keep = ['athlete_id','name','Sex','born_date','died_date','born_city','born_region','born_country','NOC','height','weight'  ]

In [ ]:
df_clean = df[columns_to_keep]

In [ ]:
df_clean['born_date'] = pd.to_datetime(df_clean['born_date'], format="mixed", errors = 'coerce')

/tmp/ipykernel_1258/3525886220.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['born_date'] = pd.to_datetime(df_clean['born_date'], format="mixed", errors = 'coerce')

In [ ]:
df_clean.head()

,athlete_id,name,Sex,born_date,died_date,born_city,born_region,born_country,NOC,height,weight
0,1,Jean-François Blanchy,Male,1886-12-12,1960-10-02,Bordeaux,Gironde,FRA,France,NaN,NaN
1,2,Arnaud Boetsch,Male,1969-04-01,NaT,Meulan,Yvelines,FRA,France,183.0,76.0
2,3,Jean Borotra,Male,1898-08-13,1994-07-17,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0
3,4,Jacques Brugnon,Male,1895-05-11,1978-03-20,Paris VIIIe,Paris,FRA,France,168.0,64.0
4,5,Albert Canet,Male,1878-04-17,1930-07-25,Wandsworth,England,GBR,France,NaN,NaN

In [ ]:
# rename height to height_cm and weight to weight_kg

In [ ]:
df_clean = df_clean.rename(columns={'height':'height_cm', "weight": "weight_kg"})

In [ ]:
df_clean['NOC'].value_counts()

NOC
United States         10114
Great Britain          6421
France                 6339
Canada                 5276
Italy                  5189
                      ...
Israel Ukraine            1
Italy Spain               1
Canada Italy              1
Brazil Croatia            1
Mexico Netherlands        1
Name: count, Length: 696, dtype: int64